#!/bin/sh

#
#  STEP 1:
#  extract all Stud.IP message strings and merge them with the existing translations
#

LOCALE_RELATIVE_PATH="."
TRANSLATIONFILES_RELAVITVE_PATHS="../lib ../assets ../views ../ ../controllers"

for language in en
do
	test -f "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/media.po" && mv "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/media.po" "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/media.po.old"
	> "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/media.UTF-8.pot"
	find $TRANSLATIONFILES_RELAVITVE_PATHS \( -iname "*.php" -o -iname "*.ihtml" \) | xargs xgettext --from-code=ISO-8859-1 -j -n --language=PHP -o "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/media.UTF-8.pot"
	msgconv --to-code=iso-8859-1 "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/media.UTF-8.pot" -o "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/media.pot"
	test -f "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/media.po.old" && msgmerge "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/media.po.old" "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/media.pot" --output-file="$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/media.po"
done
